# Feature Enginering

In [32]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [89]:
df=pd.read_csv("data_set_cleaned.csv")
df

,customer_id,age,gender,city,income,education,experience_years,monthly_spending,credit_score,signup_date,has_credit_card,loan_amount,employment_type,defaulted
0,C100000,18.0,Male,faisalabad,97203.41,Bachelor,33,34323.67,728.0,2020-01-01,Yes,162409.81000,Unemployed,0
1,C100001,56.0,Female,islamabad,132084.64,Matric,20,36955.51,439.0,2020-02-01,Yes,207532.68000,Government,0
2,C100002,51.0,Female,Lahore,39789.24,Bachelor,26,30520.91,516.0,2020-03-01,Yes,261934.54000,Government,0
3,C100003,21.0,Female,islamabad,110957.74,Matric,23,34385.96,520.0,2020-04-01,No,247704.90777,Student,1
4,C100004,69.0,Female,rawalpindi,127385.88,Master,18,34126.80,715.0,2020-05-01,No,92532.55000,Business,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,C102995,52.0,Male,Lahore,61720.95,PhD,22,33887.96,744.0,2028-03-14,Yes,302254.75000,Government,0
2986,C102996,57.0,Male,rawalpindi,39240.38,PhD,14,50459.38,448.0,2028-03-15,Yes,312313.61000,Unemployed,0
2987,C102997,60.0,Male,rawalpindi,114709.11,Master,13,79268.23,334.0,2028-03-16,Yes,325664.77000,Private,0
2988,C102998,51.0,Male,Lahore,131678.22,Intermediate,31,41027.35,550.0,2028-03-17,No,322692.25000,Government,1
2989,C102999,56.0,Female,rawalpindi,47212.42,Matric,21,32045.86,702.0,2028-03-18,No,268983.69000,Government,0

In [92]:
df.isnull().sum()

customer_id         0
age                 0
gender              0
city                0
income              0
education           0
experience_years    0
monthly_spending    0
credit_score        0
signup_date         0
has_credit_card     0
loan_amount         0
employment_type     0
defaulted           0
dtype: int64

In [93]:
df.to_csv("cleaned_data.csv", index=False)

In [94]:
df = df.drop(columns=["customer_id"])

In [95]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2990 entries, 0 to 2989
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               2990 non-null   float64
 1   gender            2990 non-null   str
 2   city              2990 non-null   str
 3   income            2990 non-null   float64
 4   education         2990 non-null   str
 5   experience_years  2990 non-null   int64
 6   monthly_spending  2990 non-null   float64
 7   credit_score      2990 non-null   float64
 8   signup_date       2990 non-null   str
 9   has_credit_card   2990 non-null   str
 10  loan_amount       2990 non-null   float64
 11  employment_type   2990 non-null   str
 12  defaulted         2990 non-null   int64
dtypes: float64(5), int64(2), str(6)
memory usage: 303.8 KB

# Encoding the Columns

### Gender

In [96]:
df["gender"].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [97]:
df["gender"]=df["gender"].map({
    "Male" : 1,
    "Female" : 0,
})

### City

In [98]:
df["city"].unique() ## use One hot encoding method

<StringArray>
['faisalabad', 'islamabad', 'Lahore', 'rawalpindi', 'karachi', 'Unknown']
Length: 6, dtype: str

In [99]:
df["city"]

0       faisalabad
1        islamabad
2           Lahore
3        islamabad
4       rawalpindi
           ...
2985        Lahore
2986    rawalpindi
2987    rawalpindi
2988        Lahore
2989    rawalpindi
Name: city, Length: 2990, dtype: str

In [100]:
df = pd.get_dummies(
    df,
    columns=["city"],
    drop_first=True,
    dtype=int
)

In [101]:
df.head()

,age,gender,income,education,experience_years,monthly_spending,credit_score,signup_date,has_credit_card,loan_amount,employment_type,defaulted,city_Unknown,city_faisalabad,city_islamabad,city_karachi,city_rawalpindi
0,18.0,1,97203.41,Bachelor,33,34323.67,728.0,2020-01-01,Yes,162409.81000,Unemployed,0,0,1,0,0,0
1,56.0,0,132084.64,Matric,20,36955.51,439.0,2020-02-01,Yes,207532.68000,Government,0,0,0,1,0,0
2,51.0,0,39789.24,Bachelor,26,30520.91,516.0,2020-03-01,Yes,261934.54000,Government,0,0,0,0,0,0
3,21.0,0,110957.74,Matric,23,34385.96,520.0,2020-04-01,No,247704.90777,Student,1,0,0,1,0,0
4,69.0,0,127385.88,Master,18,34126.80,715.0,2020-05-01,No,92532.55000,Business,0,0,0,0,0,1

In [102]:
df["education"].unique()

<StringArray>
['Bachelor', 'Matric', 'Master', 'Unknown', 'PhD', 'Intermediate']
Length: 6, dtype: str

In [103]:
df = pd.get_dummies(
    df,
    columns=["education"],
    drop_first=True,
    dtype=int
)

In [104]:
df.head()

,age,gender,income,experience_years,monthly_spending,credit_score,signup_date,has_credit_card,loan_amount,employment_type,...,city_Unknown,city_faisalabad,city_islamabad,city_karachi,city_rawalpindi,education_Intermediate,education_Master,education_Matric,education_PhD,education_Unknown
0,18.0,1,97203.41,33,34323.67,728.0,2020-01-01,Yes,162409.81000,Unemployed,...,0,1,0,0,0,0,0,0,0,0
1,56.0,0,132084.64,20,36955.51,439.0,2020-02-01,Yes,207532.68000,Government,...,0,0,1,0,0,0,0,1,0,0
2,51.0,0,39789.24,26,30520.91,516.0,2020-03-01,Yes,261934.54000,Government,...,0,0,0,0,0,0,0,0,0,0
3,21.0,0,110957.74,23,34385.96,520.0,2020-04-01,No,247704.90777,Student,...,0,0,1,0,0,0,0,1,0,0
4,69.0,0,127385.88,18,34126.80,715.0,2020-05-01,No,92532.55000,Business,...,0,0,0,0,1,0,1,0,0,0

In [105]:
df["signup_date"].unique()

<StringArray>
['2020-01-01', '2020-02-01', '2020-03-01', '2020-04-01', '2020-05-01',
 '2020-06-01', '2020-07-01', '2020-08-01', '2020-09-01', '2020-10-01',
 ...
 '2028-09-03', '2028-10-03', '2028-11-03', '2028-12-03', '2028-03-13',
 '2028-03-14', '2028-03-15', '2028-03-16', '2028-03-17', '2028-03-18']
Length: 2970, dtype: str

In [106]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [107]:
# Check that signup_date exists
print(df["signup_date"].head())

# Convert signup_date to datetime
df["signup_date"] = pd.to_datetime(df["signup_date"])

# Create year feature
df["signup_year"] = df["signup_date"].dt.year

# Show year counts
print(df["signup_year"].value_counts().sort_index())

0   2020-01-01
1   2020-02-01
2   2020-03-01
3   2020-04-01
4   2020-05-01
Name: signup_date, dtype: datetime64[us]
signup_year
2020    362
2021    363
2022    361
2023    369
2024    373
2025    366
2026    361
2027    359
2028     76
Name: count, dtype: int64

In [108]:
future_dates = df[df["signup_date"] > "2026-08-30"]

print(future_dates.shape)

(558, 22)

In [109]:
df = df[df["signup_date"] <= "2026-08-30"].copy()

In [110]:
print(df["signup_date"].max())
print(df.shape)

2026-08-30 00:00:00
(2432, 22)

In [111]:
df["signup_year"] = df["signup_date"].dt.year
df["signup_month"] = df["signup_date"].dt.month
df["signup_day"] = df["signup_date"].dt.day
df["signup_dayofweek"] = df["signup_date"].dt.dayofweek

In [112]:
df = df.drop(columns=["signup_date"])

In [113]:
df[["signup_year", "signup_month", "signup_day", "signup_dayofweek"]].head()

   signup_year  signup_month  signup_day  signup_dayofweek
0         2020             1           1                 2
1         2020             2           1                 5
2         2020             3           1                 6
3         2020             4           1                 2
4         2020             5           1                 4

In [114]:
df["has_credit_card"].unique()

<StringArray>
['Yes', 'No', 'no', 'Y', 'YES', 'N', 'yes']
Length: 7, dtype: str

In [115]:
df["has_credit"] = df["has_credit_card"].str.strip().str.lower()

df["has_credit_card"] = df["has_credit_card"].replace({
    "YES": "Yes",
    "Y": "Yes",
    "yes": "Yes",
    "no" : "No",
    "N" : "No",
    "n" : "No",
    "y" : "Yes"
})
df.value_counts("has_credit")

has_credit
yes    1584
no      833
n         8
y         7
Name: count, dtype: int64

In [116]:
df["has_credit_card"] = df["has_credit_card"].map({
    "Yes": 1,
    "No": 0
})

In [117]:
df["employment_type"].unique()

<StringArray>
['Unemployed', 'Government', 'Student', 'Business', 'Private']
Length: 5, dtype: str

In [118]:
df = pd.get_dummies(
    df,
    columns=["employment_type"],
    drop_first=True,
    dtype=int
)

In [119]:
df.head()

,age,gender,income,experience_years,monthly_spending,credit_score,has_credit_card,loan_amount,defaulted,city_Unknown,...,education_Unknown,signup_year,signup_month,signup_day,signup_dayofweek,has_credit,employment_type_Government,employment_type_Private,employment_type_Student,employment_type_Unemployed
0,18.0,1,97203.41,33,34323.67,728.0,1,162409.81000,0,0,...,0,2020,1,1,2,yes,0,0,0,1
1,56.0,0,132084.64,20,36955.51,439.0,1,207532.68000,0,0,...,0,2020,2,1,5,yes,1,0,0,0
2,51.0,0,39789.24,26,30520.91,516.0,1,261934.54000,0,0,...,0,2020,3,1,6,yes,1,0,0,0
3,21.0,0,110957.74,23,34385.96,520.0,0,247704.90777,1,0,...,0,2020,4,1,2,no,0,0,1,0
4,69.0,0,127385.88,18,34126.80,715.0,0,92532.55000,0,0,...,0,2020,5,1,4,no,0,0,0,0

In [79]:
print(df.columns.tolist())

['age', 'gender', 'income', 'experience_years', 'monthly_spending', 'credit_score', 'has_credit_card', 'loan_amount', 'defaulted', 'city_Unknown', 'city_faisalabad', 'city_islamabad', 'city_karachi', 'city_rawalpindi', 'education_Intermediate', 'education_Master', 'education_Matric', 'education_PhD', 'education_Unknown', 'signup_year', 'signup_month', 'signup_day', 'signup_dayofweek', 'has_credit', 'employment_type_Government', 'employment_type_Private', 'employment_type_Student', 'employment_type_Unemployed']

In [120]:
df.head()

,age,gender,income,experience_years,monthly_spending,credit_score,has_credit_card,loan_amount,defaulted,city_Unknown,...,education_Unknown,signup_year,signup_month,signup_day,signup_dayofweek,has_credit,employment_type_Government,employment_type_Private,employment_type_Student,employment_type_Unemployed
0,18.0,1,97203.41,33,34323.67,728.0,1,162409.81000,0,0,...,0,2020,1,1,2,yes,0,0,0,1
1,56.0,0,132084.64,20,36955.51,439.0,1,207532.68000,0,0,...,0,2020,2,1,5,yes,1,0,0,0
2,51.0,0,39789.24,26,30520.91,516.0,1,261934.54000,0,0,...,0,2020,3,1,6,yes,1,0,0,0
3,21.0,0,110957.74,23,34385.96,520.0,0,247704.90777,1,0,...,0,2020,4,1,2,no,0,0,1,0
4,69.0,0,127385.88,18,34126.80,715.0,0,92532.55000,0,0,...,0,2020,5,1,4,no,0,0,0,0

In [121]:
df = df.drop(columns=["has_credit"])

In [123]:
df.head()

,age,gender,income,experience_years,monthly_spending,credit_score,has_credit_card,loan_amount,defaulted,city_Unknown,...,education_PhD,education_Unknown,signup_year,signup_month,signup_day,signup_dayofweek,employment_type_Government,employment_type_Private,employment_type_Student,employment_type_Unemployed
0,18.0,1,97203.41,33,34323.67,728.0,1,162409.81000,0,0,...,0,0,2020,1,1,2,0,0,0,1
1,56.0,0,132084.64,20,36955.51,439.0,1,207532.68000,0,0,...,0,0,2020,2,1,5,1,0,0,0
2,51.0,0,39789.24,26,30520.91,516.0,1,261934.54000,0,0,...,0,0,2020,3,1,6,1,0,0,0
3,21.0,0,110957.74,23,34385.96,520.0,0,247704.90777,1,0,...,0,0,2020,4,1,2,0,0,1,0
4,69.0,0,127385.88,18,34126.80,715.0,0,92532.55000,0,0,...,0,0,2020,5,1,4,0,0,0,0

In [125]:
df.info()

<class 'pandas.DataFrame'>
Index: 2432 entries, 0 to 2933
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         2432 non-null   float64
 1   gender                      2432 non-null   int64
 2   income                      2432 non-null   float64
 3   experience_years            2432 non-null   int64
 4   monthly_spending            2432 non-null   float64
 5   credit_score                2432 non-null   float64
 6   has_credit_card             2432 non-null   int64
 7   loan_amount                 2432 non-null   float64
 8   defaulted                   2432 non-null   int64
 9   city_Unknown                2432 non-null   int64
 10  city_faisalabad             2432 non-null   int64
 11  city_islamabad              2432 non-null   int64
 12  city_karachi                2432 non-null   int64
 13  city_rawalpindi             2432 non-null   int64
 14  education_Intermediate      2432 non-null   int64
 15  education_Master            2432 non-null   int64
 16  education_Matric            2432 non-null   int64
 17  education_PhD               2432 non-null   int64
 18  education_Unknown           2432 non-null   int64
 19  signup_year                 2432 non-null   int32
 20  signup_month                2432 non-null   int32
 21  signup_day                  2432 non-null   int32
 22  signup_dayofweek            2432 non-null   int32
 23  employment_type_Government  2432 non-null   int64
 24  employment_type_Private     2432 non-null   int64
 25  employment_type_Student     2432 non-null   int64
 26  employment_type_Unemployed  2432 non-null   int64
dtypes: float64(5), int32(4), int64(18)
memory usage: 494.0 KB

In [126]:
df.to_csv("data_set_feature_engineered.csv", index=False)